 global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s
 scrape_configs:
  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['proposta:8181']
  - job_name: 'contas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['contas:8888']
